server:
  port: 9030
  servlet.context-path: /intelligence

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/codepilot-intelligence-db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver

  ai:
    openai: 
      api-key: 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
      base-url: https://openrouter.ai/api/v1       # Fixed: Appended /v1
      chat:
        options:
          model: openrouter/free      # Verified OpenRouter model ID
          temperature: 0.0


logging:
  level:
    org.springframework.ai: DEBUG
    org.springframework.ai.openai: DEBUG
    com.openai: DEBUG
    okhttp3: DEBUG
